name: ci
on:
  push:
    branches:
      - master
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install
        working-directory: ./.publish
        run: |
          pip install -r requirements.txt
          pip install git+git://github.com/Mara-Li/mkdocs-tooltipster-links-plugin
      - name: Create file
        run: |
          echo vault=../ > /opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/mkdocs_obsidian/.mkdocs_obsidian
          echo blog_path=./docs >> /opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/mkdocs_obsidian/.mkdocs_obsidian
          echo blog=https://valentine195.github.io/Obsidian-Vault/ >> /opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/mkdocs_obsidian/.mkdocs_obsidian
          echo share=share >> /opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/mkdocs_obsidian/.mkdocs_obsidian
          echo index_key="" >> /opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/mkdocs_obsidian/.mkdocs_obsidian
          echo default_blog="notes" >> /opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/mkdocs_obsidian/.mkdocs_obsidian
      - name: Deploy
        run: |
          obs2mk
          mkdocs gh-deploy --force
