name: ci
on:
    push:
        branches:
            - master
            - main

jobs:
    install:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-python@v2
              with:
                  python-version: 3.x

            - name: Install
              working-directory: ./.publish
              run: |
                  pip install -r requirements.txt
    setup:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-python@v2
              with:
                  python-version: 3.x
            - uses: jannekem/run-python-script-action@v1
              with:
                  script: |
                      import mkdocs_obsidian as obs
                      os.environ['BASEDIR'] = obs.__path__[0]
                        - name: Create file
              run: |
                  echo vault="../" > ${{env.BASEDIR}}/.mkdocs_obsidian
                  echo blog_path="./" >> ${{env.BASEDIR}}/.mkdocs_obsidian
                  echo blog="https://valentine195.github.io/Obsidian-Vault/" >> ${{env.BASEDIR}}/.mkdocs_obsidian
                  cat ${{env.BASEDIR}}/.mkdocs_obsidian
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-python@v2
              with:
                  python-version: 3.x
            - name: Deploy
              working-directory: ./.publish
              run: |
                  obs2mk --git
                  mkdocs gh-deploy --force
